server:
  port: 8443
  tomcat:
    uri-encoding: utf-8
    max-http-header-size: 8096
  ssl:
    key-alias: tomcat
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    enabled: true
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
    include: include

